config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'home#index'

  match 'home' => 'home#index', via: 'get'
  match 'inicio' => 'home#index', via: 'get'
  match 'cidade/search' => 'cidade#search', via: 'get'

  get 'complaints/' => 'complaints#index'
  get 'sign_out;' => 'devise/sessions#destroy'
  get '/:cidade/', to: 'cidade#show', as: 'cidades'
  get '/:cidade/reclamar', to: 'complaints#new', as: 'reclamar'

  resources :complaints , path_names: { new: 'criar' } do
     get 'liked' => 'complaints#liked' , on: :collection
     post 'like' => 'complaints#like'
  end

  post 'complaints/abuse' => 'complaints#abuse'
  post 'complaints/reply' => 'complaints#reply'
  post 'email/contato' => 'home#contato' , :defaults => { :format => 'json' }

  devise_for :users, controllers: {registrations:"registrations", :omniauth_callbacks => "users/omniauth_callbacks"}
  devise_scope :user do
    get 'users/logout', :to => 'devise/sessions#destroy', :as => :logout_user
  end

end

app/controllers/home_controller.rb
# Controller da pagina inicial
class HomeController < ApplicationController
  def index
    @complaint_list = Complaint.all
    @lastest = Complaint.last(10).reverse
    @categories = Category.all
    @logado = user_signed_in?
  end

  def contato
    response = { status: 'success' }
    begin
      IndexMailer.contato(params[:nome], params[:email], params[:entidade],
                          params[:telefone]).deliver_later
    rescue => ex
      logger.debug ex
      response.status = 'error'
    end
    respond_to do |format|
      format.html { render nothing: true, status: 200 }
      format.json { render json: response, status: 200 }
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% content_for :opg do%>
  <title>Minha rua tem problema - Os problemas de sua cidade</title>
  <meta property="og:title" content="Minha rua tem problema | Acompanhe sua cidade" />
  <meta property="og:description" content="Está insatisfeito com as condições de sua rua ? Acesse e deixe sua reclamação!" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="https://www.minharuatemproblema.com.br" />
  <meta property="og:image" content="https://www.minharuatemproblema.com.br/assets/images/denuncia.jpg" />
<% end %>
<section class="featured">
	<!-- <video autoplay loop poster="images/video.png"><source src="/assets/videos/video1.mp4"></video> -->
	<div class="box">
		<h2>Selecione uma cidade e acompanhe os problemas cadastrados!</h2>
		<input type="text" id="city-input-home" class="city-input-home" placeholder="Sua cidade">
		<a href="#contato">Sou do setor público</a>
	</div>
</section>
<!-- <section class="walkthrough">
	<div class="container">
		<div class="row">
			<div class="col-sm-3 col-xs-4 new-size-offset col-sm-offset-2">
				<div class="step">
					<div class="icon">
						<i class="fa fa-map-marker" aria-hidden="true"></i>
					</div>
					<h3>Crie sua conta.</h3>
				</div>
			</div>
			<div class="col-sm-3 col-xs-4">
				<div class="step">
					<div class="icon">
						<i class="fa fa-map-marker" aria-hidden="true"></i>
					</div>
					<h3>Selecione o endereço e preencha a reclamação</h3>
				</div>
			</div>
			<div class="col-sm-3 col-xs-12">
				<div class="step">
					<div class="icon">
						<i class="fa fa-map-marker" aria-hidden="true"></i>
					</div>
					<h3>Tudo pronto. Agora compartilhe a reclamação em suas redes sociais </h3>
				</div>
			</div>

		</div>
	</div>
</section> -->
<section class="video container">
	<div class="row">
		<div class="col-xs-12">
			<h2>Sobre nosso projeto</h2>
			<h3>Cadastre-se, reclame e compartilhe, pois com o esforço coletivo esta será a nossa ferramenta para fiscalizar e melhorar nossas cidades.</h3>
		</div>
		<div class="col-xs-12">
			<iframe width="560" height="315" src="https://www.youtube.com/embed/7KF9D_mzRIc" frameborder="0" allowfullscreen></iframe>
		</div>
		<div class="col-xs-12">
			<div class="need-you">

				<h2>Porque precisamos da sua ajuda ?</h2>
				<p class="light">Atualmente estamos em uma fase crítica da projeto. Como estamos iniciando e sem nenhum recurso financeiro para divulgação as prefeituras ainda não nós recebem e não sabem do projeto, <strong>por isso precisamos do apoio de todos para criarem o maior número de reclamações nos diversos locais e cidades</strong>, assim conseguiremos provar através da pressão popular que nosso sistema funciona.</p>
			</div>
		</div>
	</div>
</section>
<section class="help">
	<div class="container">
		<div class="text">
			<h2>Como podemos melhorar as cidades ?</h2>
			<p  class="">Fiscalizando. Como qualquer pessoa tem acesso ao site todos podem acompanhar e relatar problemas, gerando um histórico de quanto tempo aquele problema ficou sem ser resolvido.  </p>
		</div>
	</div>
</section>
<section class="setor-publico">
	<div class="container">
		<div class="text">
			<h2>Setor Público</h2>
			<p>Caso queira utilizar nossa ferramenta para gerenciar os problemas de sua cidade, preencha o formulário abaixo e entraremos em contato com você em breve.</p>
			
			<form id="contato">
				<div class="row">
					<div class="col-sm-offset-3 col-sm-6">
						<input type="text" name="nome" placeholder="Nome" id="nome">
					</div>
					<div class="col-sm-offset-3 col-sm-6">
						<input type="text" name="telefone" placeholder="Telefone" id="telefone">
					</div>
					<div class="col-sm-offset-3 col-sm-6">
						<input type="email" name="email" placeholder="E-mail" id="emails">
					</div>
					<div class="col-sm-offset-3 col-sm-6">
						<input type="text" name="entidade" placeholder="Entidade pública" id="entidade">
					</div>
					<div class="col-sm-offset-3 col-sm-6">
						<input type="submit" value="Enviar" id="enviar"/>
						<div id="loading" style="display:none">
							<i class="fa fa-spinner fa-pulse fa-3x fa-fw"></i>
							<span class="sr-only">Loading...</span>
						</div>
						<div id="success" style="display:none">Mensagem enviada com sucesso!</div>
					</div>

				</div>
			</form>
		</div>
	</div>
</section>
<footer></footer>

<script>
	$('#enviar').click(function(){
		var datastring = $('#contato').serialize();

		$.ajax({
		    type: "post",
		    url: "/email/contato",
		    data: datastring,
		    dataType: "json",
		    success: function(data) {
		    	console.log('success');
		        console.log(data);
		        if(data.status == 'success'){
		        	console.log('success');
		        	$('#contato').html('<h2>Mensagem enviada</h2>').fadeIn();
		        }
		    },
		    error: function(data){
		    	console.log('erro');
		    	console.log(data);
		    },
          beforeSend: function(){
          	$('#enviar').hide();
            $('#loading').show();
          },
          complete: function(){
          	$('#enviar').show();
            $('#loading').hide();
            $('#contato input[type=text],input[type=email]').val('');
          }
		});

		return false;
	})
</script>

app/views/home/old-index.html.erb
<% content_for :opg do%>
  <title>Minha Rua Tem Problema</title>
  <meta property="og:title" content="Minha rua tem problema - Deixe sua reclamação" />
  <meta property="og:description" content="Está insatisfeito com as condições de sua rua ? Acesse e deixe sua reclamação!" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="https://www.minharuatemproblema.com.br" />
  <meta property="og:image" content="https://www.minharuatemproblema.com.br/assets/images/denuncia.jpg" />
<% end %>
<div id="home">
  <div id="question-city">
    <div class="box">
      <div class="container-fluid">
        <div class="row">
          <div class="col-xs-12">
            <h2>Acompanhe os problemas que acontece em sua cidade.</h2>
            <div class="field">
              <input type="text" class="city-input" placeholder="Digite uma cidade...">
            </div>
          </div>
        </div>
         <div class="row ">
            <div class="col-xs-12">
              <div id="error"></div>
            </div>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
  <div class="tool-bar">
    <div class="helpus">
      <i class="fa fa-exclamation" aria-hidden="true"></i>
    </div>
  </div>
  <div class="tool-content">
    <div class="helpus">
      <div class="close">
        <i class="fa fa-times-circle-o" aria-hidden="true"></i>
      </div>
      <h3>Precisamos da sua ajuda!</h3>
      <h5>COMPARTILHE, e COMPARTILHE...</h5>
      <p>Ola amigo(a), nosso projeto ainda é pequeno e por isso as prefeituras não estão olhando para nós, mas não deixe de postar sua reclamação, nosso objetivo neste momento é fazer PRESSÃO! </p>
      <p>Para conseguirmos a atenção dos responsáveis precisamos reunir o maior número de reclamações nos diversos pontos da cidade, assim eles verão que NÓS TEMOS VOZ! Portanto, <b>COMPARTILHE!</b></p>
      <p>Envie o link de nosso site para todos os seus amigos e incentive-os a reclamar!  </p>
      <p>Se você é de alguma prefeitura ou orgão responsavel envie um e-mail com seu contato para minharuatemproblema@gmail.com</p>
      
      <h3>Curta nossa página no facebook!</h3>

      <div class="fb-page" data-href="https://www.facebook.com/minharuatemproblema" data-height="300" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/minharuatemproblema" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/minharuatemproblema">Minha rua tem problema</a></blockquote></div>
    </div>
  </div> 

  <div id="map"></div>

  <section class="categories hidden-xs">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="button-icons">
            <ul>
                <li>
                  <a href="#!" class="filter-category"  data-tag="all"><img src="/assets/images/categories/clear.png" alt=""><br>Limpar filtros</a>
                </li>
              <% @categories.each do |category| %>
                <li>
                  <a href="#!" class="filter-category <%=raw "#{category.tag}"%>"  data-tag="<%=raw "#{category.tag}"%>"><img src="/assets/images/categories/<%=raw "#{category.tag}"%>.png" alt=""><br><%=raw "#{category.title}" %></a>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>
  <div class="mobile-tools visible-xs">
    <div class="row">
      <div class="col-xs-6 search">
        <a id="search-mobile">BUSCAR</a>
      </div>
      <div class="col-xs-6 new">
        <a href="#!"><%= link_to('RECLAMAR', new_complaint_path)  %></a>
      </div>
    </div>
  </div>

  <div class="input-search-mobile visible-xs">
    <form id="form-searc-mobile">
      <input type="text" id="city-input-mobile" class="city-input"  placeholder="Digite sua cidade...">
    </form>
  </div>
<div id="home-big"></div>

<script type="text/javascript">
    var cities = []
    var map;
    var geocoder;
     var openedInfoWindow = null
      $( function() {
         $( document ).tooltip();
      });

    function initMap() {
        var myLatlng = new google.maps.LatLng(-14.235004,-51.92528);
        geocoder = new google.maps.Geocoder();
        map = new google.maps.Map(document.getElementById('map'), {
          center: myLatlng,
          zoom: 4,
          mapTypeControl: false,
          zoomControl: true,
          zoomControlOptions: {
              position: google.maps.ControlPosition.RIGHT_CENTER
          },

          scaleControl: false,
          streetViewControl: false,
          
        });
        
    }
    checkMap();
    $('#my-place').click(function(){
      if (navigator.geolocation) {
        //coloca mapa na localização da pessoa
        navigator.geolocation.getCurrentPosition(function(position) {
            var pos = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };
            map.setCenter(pos);
            map.setZoom(14);

            var latitude = pos.lat;
            var longitude = pos.lng;
            localStorage.setItem("latitude", latitude);
            localStorage.setItem("longitude", longitude);

            setTimeout(function(){$('#question-city').css('top','100%');},200)
          }, function(error) {
            console.log("Erro geolocation: "+error.code);
            console.log(error)
            if(error.code == 0){
                $('.box #error').text('Erro desconhecico. Tente novamente mais tarde!');
            }else if(error.code == 1){
              $('.box #error').text('Você não compartilhou sua localização com nossa aplicação. Certifique que seu GPS esteja ligado e tente novamente!');
            }else if(error.code == 2){
              $('.box #error').text('Nao foi possível obter sua localização. Certifique-se que seu GPS esteja ligado e tente novamente.');
            }else if(error.code == 3){
              $('.box #error').text('A resposta demorou demais. Tente novamente.');
            }else{
              $('.box #error').text('Você não compartilhou sua localização com nossa aplicação!');
            }


            setTimeout(function(){
              $('.box #error').text('');
            },2000)

            // error.code can be:
            //   0: unknown error
            //   1: permission denied
            //   2: position unavailable (error response from locaton provider)
            //   3: timed out
          });
        } else {
          // Browser doesn't support Geolocation
                      console.log(erro)
          // handleLocationError(false, infoWindow, map.getCenter());
        }
    });


</script>