config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'home#index'

  match 'home' => 'home#index', via: 'get'
  match 'inicio' => 'home#index', via: 'get'
  match 'cidade/search' => 'cidade#search', via: 'get'

  get 'complaints/' => 'complaints#index'
  get 'sign_out;' => 'devise/sessions#destroy'
  get '/:cidade/', to: 'cidade#show', as: 'cidades'
  get '/:cidade/reclamar', to: 'complaints#new', as: 'reclamar'

  resources :complaints , path_names: { new: 'criar' } do
     get 'liked' => 'complaints#liked' , on: :collection
     post 'like' => 'complaints#like'
  end

  post 'complaints/abuse' => 'complaints#abuse'
  post 'complaints/reply' => 'complaints#reply'
  post 'email/contato' => 'home#contato' , :defaults => { :format => 'json' }

  devise_for :users, controllers: {registrations:"registrations", :omniauth_callbacks => "users/omniauth_callbacks"}
  devise_scope :user do
    get 'users/logout', :to => 'devise/sessions#destroy', :as => :logout_user
  end

end

app/views/layouts/_modal_cidade.html.erb
<div class="modal fade"  id="modalCidadeReclamar" tabindex="-1" role="dialog" aria-labelledby="modalCidadeReclamar">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <h2>Selecione uma cidade para reclamação</h2>
	   <input type="text" id="city-input" class="city-input sem-cidade"  placeholder="Digite uma cidade..." data-reclamar="TRUE">
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
	 <!-- Chrome, Firefox OS and Opera -->
	<meta name="theme-color" content="#121F25">
	<!-- Windows Phone -->
	<meta name="msapplication-navbutton-color" content="#121F25">
	<!-- iOS Safari -->
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
	<%= yield :opg %>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

	<%= csrf_meta_tags %>
	<%= analytics_init if GoogleAnalytics.valid_tracker? %>
</head>
<body>
	 <% flash.each do |type, message| %>
          <div class="alert alert-<%= type %> toast">
              <button class="close" data-dismiss="alert">×</button>
              <%= message %>
          </div>
      <% end %>
	<nav class="navbar navbar-default">
	  <div class="container">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="/#!" style="padding-top:3px;"><img src="/assets/images/minha-rua-logo.png" alt=""></a>
	      <div class="actual-city visible-xs" id="search-mobile">
	      	<h2><%= @city ? @city.nome : 'Escolher cidade' %></h2>
	      	<a href="#!">Trocar cidade</a>
	      </div>
	    </div>
	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav navbar-right">
	        <li><div class="actual-city hidden-xs">
	      	<h2><%= @city ? @city.nome : 'Escolher cidade' %></h2>
	      	<a href="#!">Trocar cidade</a>
	      </div></li>
				<% if @city %>
					<li class="menu-add hidden-xs"> <a href="/<%= @city.slug%>/reclamar">Reclamar</a> </li>
				<% else %>
					<li class="menu-add hidden-xs"> <a href="#!" data-toggle="modal" data-target="#modalCidadeReclamar" id="reclamarSemCidade">Reclamar</a> </li>
				<% end %>
            <li class="dropdown">
                <a <%= current_user ? 'href=# class=dropdown-toggle data-toggle=dropdown' : 'href=/users/sign_in' %> >
                    <span class="glyphicon glyphicon-user"></span>
                    <strong> &nbsp;<%= current_user ? current_user.first_name : "Login" %></strong>
                    <% if current_user %>
                    	<span class="glyphicon glyphicon-chevron-down"></span>
                    <% end %>
                    
                </a>
                <ul class="dropdown-menu user-menu">
                    <li>
                        <div class="navbar-login">
                            <div class="row">
                                <div class="col-xs-12 col-lg-4">
                                    <p class="text-center">
                                        <span class="glyphicon glyphicon-user icon-size"></span>
                                    </p>
                                </div>
                                <div class="col-xs-12 col-lg-8">
                                    <p class="text-center"><strong><%= current_user ? current_user.first_name : "Login" %></strong></p>
                                    <p class="text-center small"><%= current_user ? current_user.email : "Login" %></p>
                                   <!--  <p class="text-left">
                                        <a href="#" class="btn btn-primary btn-block btn-sm">Profile</a>
                                    </p> -->
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="divider navbar-login-session-bg"></li>
                     <li><a href="<%=raw root_path %>">Início <span class="fa fa-map pull-right"></span></a></li>
                      <li class="divider"></li>
		            <li><a href="<%=raw complaints_path %>">Minhas reclamações <span class="fa fa-bullhorn pull-right"></span></a></li>
		            <li class="divider"></li>
		            <li><a href="<%=raw liked_complaints_path %>">Reclamações apoiadas <span class="glyphicon glyphicon-heart pull-right"></span></a></li>
		            <li class="divider"></li>
		            <li><a href="<%=raw logout_user_path %>">Sair <span class="glyphicon glyphicon-log-out pull-right"></span></a></li>
		            <li class="divider visible-xs"></li>
                </ul>
            </li>
	      </ul>

	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
	<main class="<%= controller.controller_name %> <%= controller.action_name %>">
		<%= yield %>
	</main>

	<div class="input-search">
    	<form id="form-search">
     		<input type="text" id="city-input" class="city-input"  placeholder="Digite uma cidade...">
    	</form>
    	<div class="close-search">
    		<i class="fa fa-times" aria-hidden="true"></i>
    	</div>
  	</div>

  	<%= render '/layouts/modal_cidade' %>

    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCORWu-uTguiEdLaTvsFu74TPvmYE2fNrA&callback=initMap">
    </script>
</body>
</html>